#!/bin/bash

set -eE

sudo nginx -c /home/bart/Projects/Scherebart/trading/nginx.conf
function cleanup_nginx {
    echo "closing nginx..."
    sudo kill -TERM $(cat .nginx/pid)
}

trap 'echo sigint!' SIGINT
trap cleanup_nginx ERR

node server.js
